/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_ajout_cl (void);
GtkWidget* create_affiche_cl (void);
GtkWidget* create_supprim_cl (void);
GtkWidget* create_modif_cl (void);
